Repository autowarefoundation/autoware-documentation, pull requests merged in 2022-06, with the labels that each got.

#125 docs(how-to guides): how to integrate differential drive vehicles
  docs/how-to-guides/.pages
  docs/how-to-guides/how-to-integrate-autoware-with-a-diff-drive-vehicle.md
  docs/how-to-guides/index.md
Labels: documentation

#86 docs(design): add autoware design overview
  docs/design/.pages
  docs/design/autoware-architecture/.pages
  docs/design/autoware-architecture/control/index.md
  docs/design/autoware-architecture/image/autoware-architecture-overview.drawio.svg
  docs/design/autoware-architecture/index.md
  docs/design/autoware-architecture/localization/index.md
  docs/design/autoware-architecture/map/index.md
  docs/design/autoware-architecture/node-diagram/index.md
  docs/design/autoware-architecture/perception/index.md
  docs/design/autoware-architecture/planning/index.md
  docs/design/autoware-architecture/sensing/index.md
  docs/design/autoware-architecture/vehicle/index.md
  docs/design/index.md
Labels: documentation

#124 docs(tutorials): update tutorials main page
  docs/tutorials/index.md
Labels: documentation

#137 docs(installation): add minimum hardware requirements
  docs/installation/autoware/source-installation.md
  docs/installation/index.md
Labels: documentation

#119 docs(guidelines): add unit and integration testing guidelines
  docs/contributing/testing-guidelines/.pages
  docs/contributing/testing-guidelines/index.md
  docs/contributing/testing-guidelines/integration-testing.md
  docs/contributing/testing-guidelines/unit-testing.md
Labels: documentation

#142 docs(guidelines): update integration unit testing guidelines
  docs/contributing/testing-guidelines/integration-testing.md
  docs/contributing/testing-guidelines/unit-testing.md
Labels: documentation

#143 docs(tutorial): update broken link in random-test-simulation.md
  docs/tutorials/scenario-simulation/planning-simulation/random-test-simulation.md
Labels: ignore-semantic-pull-request

#140 docs(how-to guides): added documentation for maps creation
  docs/how-to-guides/.pages
  docs/how-to-guides/how-to-create-maps-for-autoware.md
  docs/how-to-guides/index.md
Labels: documentation

#149 revert: revert "feat(how-to): rename how to guide section"
  docs/how-to-guides/.pages
  docs/how-to-guides/advanced-usage-of-colcon.md
  docs/how-to-guides/how-to-create-maps-for-autoware.md
  docs/how-to-guides/how-to-integrate-autoware-with-a-diff-drive-vehicle.md
  docs/how-to-guides/how-to-integrate-autoware-with-your-vehicle.md
  docs/how-to-guides/images/how-to-integrate-autoware-with-your-vehicle/autoware-state-panel.png
  docs/how-to-guides/index.md
  docs/how-to-guides/running-autoware-without-cuda.md
  docs/how-to-guides/sensor-calibration.md
  docs/index.md
  docs/tutorials/.pages
Labels: ignore-semantic-pull-request

#151 docs(ad-api): add use cases
  docs/design/autoware-interfaces/ad-api/.pages
  docs/design/autoware-interfaces/ad-api/use-cases/.pages
  docs/design/autoware-interfaces/ad-api/use-cases/bus-service.md
  docs/design/autoware-interfaces/ad-api/use-cases/change-operation-mode.md
  docs/design/autoware-interfaces/ad-api/use-cases/drive-designated-position.md
  docs/design/autoware-interfaces/ad-api/use-cases/get-on-off.md
  docs/design/autoware-interfaces/ad-api/use-cases/index.md
  docs/design/autoware-interfaces/ad-api/use-cases/initialize-pose.md
  docs/design/autoware-interfaces/ad-api/use-cases/launch-terminate.md
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/drive-designated-position.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/get-on-off.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/initialize-pose-gnss.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/initialize-pose-input.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/launch-terminate.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/operation-mode-hardware.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/sequence/operation-mode-software.plantuml
  docs/design/autoware-interfaces/ad-api/use-cases/taxi-service.md
Labels: documentation

#150 feat: add glossary
  .gitignore
  includes/abbreviations.md
  mkdocs.yaml
Labels: documentation, enhancement
