Repository autowarefoundation/autoware-documentation, pull requests merged in 2022-11, with the labels that each got.

#217 feat(tutorial): update the section of scenario based rosbag replay simulation
  docs/tutorials/scenario-simulation/.pages
  docs/tutorials/scenario-simulation/rosbag-replay-simulation.md
  docs/tutorials/scenario-simulation/rosbag-replay-simulation/.pages
  docs/tutorials/scenario-simulation/rosbag-replay-simulation/driving-log-replayer.md
Labels: documentation

#173 docs: update sensor-calibration.md
  docs/how-to-guides/calibrating-your-sensors.md
Labels: documentation

#242 docs(installation): add DDS setting to additional-settings-for-developpers
  docs/installation/additional-settings-for-developers/index.md
Labels: documentation

#243 docs: change links of perception nodes in node diagram
  docs/design/autoware-architecture/node-diagram/overall-node-diagram-autoware-universe.drawio.svg
Labels: documentation

#184 docs(how-to guides): add documentation about controller evaluation
  docs/how-to-guides/.pages
  docs/how-to-guides/evaluating-controller-performance.md
  docs/how-to-guides/images/evaluating-controller-performance/controller-monitor.png
  docs/how-to-guides/images/evaluating-controller-performance/export-cvs.png
  docs/how-to-guides/images/evaluating-controller-performance/import-data.png
  docs/how-to-guides/images/evaluating-controller-performance/plot-xy.png
  docs/how-to-guides/images/evaluating-controller-performance/start-plotjuggler.png
  docs/how-to-guides/index.md
Labels: documentation

#245 ci(deploy-docs): rename documentation label to deploy-docs label
  .github/workflows/deploy-docs.yaml
  docs/contributing/documentation-guidelines/images/deploy-docs-label-for-pull-request.png
  docs/contributing/documentation-guidelines/images/documentation-label-for-pull-request.png
  docs/contributing/documentation-guidelines/index.md
  docs/contributing/pull-request-guidelines/ci-checks.md
Labels: deploy-docs

#254 feat(ad-api): update to latest message
  docs/design/autoware-interfaces/ad-api/list/api/fail_safe/mrm_state.md
  docs/design/autoware-interfaces/ad-api/list/api/interface/version.md
  docs/design/autoware-interfaces/ad-api/list/api/localization/initialization_state.md
  docs/design/autoware-interfaces/ad-api/list/api/localization/initialize.md
  docs/design/autoware-interfaces/ad-api/list/api/motion/accept_start.md
  docs/design/autoware-interfaces/ad-api/list/api/motion/state.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_autonomous.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_local.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_remote.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_stop.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/disable_autoware_control.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/enable_autoware_control.md
  docs/design/autoware-interfaces/ad-api/list/api/operation_mode/state.md
  docs/design/autoware-interfaces/ad-api/list/api/planning/steering_factors.md
  docs/design/autoware-interfaces/ad-api/list/api/planning/velocity_factors.md
  docs/design/autoware-interfaces/ad-api/list/api/routing/clear_route.md
  docs/design/autoware-interfaces/ad-api/list/api/routing/route.md
  docs/design/autoware-interfaces/ad-api/list/api/routing/set_route.md
  docs/design/autoware-interfaces/ad-api/list/api/routing/set_route_points.md
  docs/design/autoware-interfaces/ad-api/list/api/routing/state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/mrm_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/operation_mode_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/response_status.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/route.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/route_optional.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/route_segment.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/steering_factor_array.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/velocity_factor_array.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/accept_start.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/change_operation_mode.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/clear_route.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/initialize_localization.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/interface_version.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/set_route.md
  docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/srv/set_route_points.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/localization_initialization_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/motion_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/mrm_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/operation_mode_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/response_status.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_data.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_primitive.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_segment.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_state.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/steering_factor.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/steering_factor_array.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/velocity_factor.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/velocity_factor_array.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/accept_start.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/change_operation_mode.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/clear_route.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/initialize_localization.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/set_route.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/set_route_points.md
  docs/design/autoware-interfaces/ad-api/types/autoware_adapi_version_msgs/srv/interface_version.md
Labels: deploy-docs

#232 docs: add the manual and tutorial guideline for using morai sim
  docs/tutorials/ad-hoc-simulation/digital-twin-simulation/.pages
  docs/tutorials/ad-hoc-simulation/digital-twin-simulation/MORAI_Sim-tutorial.md
Labels: documentation

#239 docs(docker-install): add CUDA to "Installing dependencies manually"
  docs/installation/autoware/docker-installation.md
Labels: documentation, deploy-docs

#255 fix(node-diagram): update autoware.iv link to autoware.universe
  docs/design/autoware-architecture/node-diagram/overall-node-diagram-autoware-universe.drawio.svg
  docs/design/autoware-architecture/planning/image/planning-diagram.drawio.svg
Labels: documentation

#258 refactor: use macros for drawio images
  docs/design/autoware-architecture/node-diagram/index.md
  main.py
Labels: deploy-docs

#256 fix(node-diagram): fix toggle for each components
  docs/design/autoware-architecture/node-diagram/overall-node-diagram-autoware-universe.drawio.svg
Labels: deploy-docs

#259 docs(node-diagram): fix broken link
  docs/design/autoware-architecture/node-diagram/overall-node-diagram-autoware-universe.drawio.svg
Labels: documentation

#234 docs(tutorial): add how to use dummy objects interactively
  docs/tutorials/ad-hoc-simulation/images/planning/lane-following/check-interactive.png
  docs/tutorials/ad-hoc-simulation/images/planning/lane-following/move-dummy-object.png
  docs/tutorials/ad-hoc-simulation/planning-simulation.md
Labels: documentation

#261 refactor: use relative paths
  docs/contributing/index.md
  docs/design/autoware-concepts/difference-from-ai-and-auto.md
  docs/how-to-guides/evaluating-controller-performance.md
  docs/how-to-guides/integrating-autoware-with-a-diff-drive-vehicle.md
  docs/how-to-guides/integrating-autoware-with-your-vehicle.md
  docs/installation/autoware/docker-installation.md
  docs/installation/autoware/source-installation.md
  docs/installation/index.md
  docs/support/troubleshooting.md
  docs/tutorials/scenario-simulation/planning-simulation/installation.md
Labels: deploy-docs
